### ISSUE TITLE
Code for current release not uploaded

### ISSUE THREAD

**Issue by linuxgurugamer** [DBooots/ESLDBeacons#3]
A release was done a few days ago, but the code has not been uploaded yet

**Comment by DBooots** [comment]
After running a diff between my local copy and this repository, it turns out that all the changes for the latest release were in the .csproj file which is not captured in this repository. All prior changes were committed previously. The code in the repository is up-to-date at the time of commenting.

**Comment by linuxgurugamer** [comment]
All I can say is that when I decompiled the code, it was different than what was here.
I would do a PR, but it's essentially every file which got changed.  I also had changed the directories, so it might be best to clone mine locally and do either do manual diffs or just copy all the files in my repo to the correct locations in yours.

**Comment by DBooots** [comment]
I wonder if it's a matter of compiler settings or something. Anyway, I'll do a manual clone and diff from your repo. Thanks!
